In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv('train.csv')[['Age','Pclass','Fare','Survived']]

In [4]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [8]:
df.isnull().mean()*100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [9]:
# now X-y alag alag kar lete hain
X = df.drop(columns=['Survived'])
y = df['Survived']

In [10]:
# trainn test split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [14]:
X_train.head()

      Age  Pclass     Fare
30   40.0       1  27.7208
10    4.0       3  16.7000
873  47.0       3   9.0000
182   9.0       3  31.3875
876  20.0       3   9.8458

In [15]:
X_test.head()

      Age  Pclass     Fare
707  42.0       1  26.2875
37   21.0       3   8.0500
615  24.0       2  65.0000
169  28.0       3  56.4958
68   17.0       3   7.9250

In [16]:
knn = KNNImputer()

X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [17]:
pd.DataFrame(X_train_trf, columns=X_train.columns)

      Age  Pclass      Fare
0    40.0     1.0   27.7208
1     4.0     3.0   16.7000
2    47.0     3.0    9.0000
3     9.0     3.0   31.3875
4    20.0     3.0    9.8458
..    ...     ...       ...
707  30.0     3.0    8.6625
708  24.4     3.0    8.7125
709  71.0     1.0   49.5042
710  33.6     1.0  221.7792
711  42.8     1.0   25.9250

[712 rows x 3 columns]

In [18]:
lr = LogisticRegression()

lr.fit(X_train_trf,y_train)

y_pred = lr.predict(X_test_trf)
accuracy_score(y_test,y_pred)

0.7039106145251397

In [19]:
# comparision with simple Imputer ---> mean

si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [20]:
lr = LogisticRegression()

lr.fit(X_train_trf2,y_train)

y_pred2 = lr.predict(X_test_trf2)
accuracy_score(y_test,y_pred2)

0.6927374301675978